#include "main.h"
#include "adc.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

#include <stdbool.h>
#include <stdio.h>
#include <string.h>

/*
 * Teaching overview
 * -----------------
 * This file is the top-level firmware scaffold for the MPPT practical. It ties
 * together the STM32 peripherals generated by CubeMX, the converter state
 * machine, ADC measurement conversion, PWM gate-driver control, serial commands,
 * and the student MPPT algorithm hook.
 *
 * The most important point for students is separation of responsibilities:
 *   - ADC code measures the PV/input and output quantities.
 *   - The state machine decides when switching is allowed.
 *   - Power-stage functions are the only functions that touch PWM and driver
 *     enable pins.
 *   - Mppt_CalculateDuty() is the intended place to add the MPPT algorithm.
 *
 */
typedef enum
{
  MPPT_STATE_INIT = 0,  /* Boot/configuration state before normal control starts. */
  MPPT_STATE_IDLE,      /* PWM stopped, gate drivers disabled, measurements active. */
  MPPT_STATE_STARTUP,   /* Conservative first switching state before MPPT is allowed. */
  MPPT_STATE_RUN,       /* Normal closed-loop MPPT update state. */
  MPPT_STATE_FAULT      /* Safe latched state entered after invalid feedback or PWM failure. */
} MpptState_t;

/*
 * Fault reasons recorded by the state machine.
 *
 * The fault code is deliberately small: it is easy to print over UART and easy
 * for students to inspect in the debugger. More detailed projects can add
 * over-voltage, over-current, and temperature faults here.
 */
typedef enum
{
  MPPT_FAULT_NONE = 0,
  MPPT_FAULT_ADC_READ,
  MPPT_FAULT_ADC_RANGE,
  MPPT_FAULT_PWM_START
} MpptFault_t;

/*
 * One snapshot of the converter measurements.
 *
 * Each physical signal appears in three forms:
 *   1. raw ADC counts, useful for debugging ADC configuration;
 *   2. ADC pin voltage, useful for checking sensor interface circuits;
 *   3. engineering units, used by the MPPT and fault logic.
 */
typedef struct
{
  /* Raw 12-bit ADC results from the STM32 ADC peripherals. */
  uint16_t i_in_raw;
  uint16_t i_out_raw;
  uint16_t v_out_raw;
  uint16_t v_in_raw;

  /* Voltages actually present at the STM32 ADC pins, in the 0 V to 3.3 V range. */
  float i_in_adc_v;
  float i_out_adc_v;
  float v_out_adc_v;
  float v_in_adc_v;

  /* Converted quantities at the converter terminals. */
  float i_in_a;
  float i_out_a;
  float v_out_v;
  float v_in_v;
  float pv_power_w;

  /* Validity and timestamp help the control code reject stale or failed reads. */
  bool valid;
  uint32_t updated_ms;
} MpptMeasurements_t;

/*
 * Duty-cycle command for the two half bridges of the four-switch buck-boost.
 * Values are normalised fractions, not timer counts: 0.25 means 25% duty.
 */
typedef struct
{
  float buck_duty;
  float boost_duty;
} MpptDutyCommand_t;

/* ADC conversion and basic plausibility limits. */
#define ADC_REFERENCE_VOLTAGE      (3.3f)
#define ADC_MAX_COUNTS             (4095.0f)
#define ADC_POLL_TIMEOUT_MS        (2U)
#define ADC_RAW_SATURATION_COUNT   (4090U)

/* Sensor scale factors from the voltage/current sensing equations in the guide. */
#define INPUT_VOLTAGE_SENSOR_SCALE (46.45f)
#define OUTPUT_VOLTAGE_SENSOR_SCALE (28.78f)
#define INPUT_CURRENT_SENSOR_V_PER_A (0.100f)
#define OUTPUT_CURRENT_SENSOR_V_PER_A (0.0333f)

/*
 * Cooperative scheduler periods.
 *
 * The main loop has no RTOS. Instead, it calls short tasks when their elapsed
 * time has expired. Measurement/protection runs fastest; MPPT runs slower so
 * the converter can settle after a duty change; telemetry is rate-limited so
 * UART printing does not dominate the control loop.
 */
#define FAST_TASK_PERIOD_MS        (1U)
#define MPPT_TASK_PERIOD_MS        (50U)
#define TELEMETRY_TASK_PERIOD_MS   (100U)
#define STARTUP_SETTLE_TIME_MS     (500U)

/* Duty limits and conservative startup command. */
#define DUTY_MIN                   (0.0f)
#define DUTY_MAX                   (0.95f)
#define STARTUP_BUCK_DUTY          (0.05f)
#define STARTUP_BOOST_DUTY         (0.0f)

/*
 * LD3 test pattern configuration.
 * PB3 is shared with the PCB signal BST_STP, so this LED feature is intended
 * for MCU-only testing, not for an energised converter.
 */
#define LD3_STATUS_TEST_ENABLE     (1U)
#define LD3_IDLE_PERIOD_MS         (4000U)
#define LD3_IDLE_ON_TIME_MS        (1000U)
#define LD3_RUN_PERIOD_MS          (200U)
#define LD3_RUN_ON_TIME_MS         (100U)

/*
 * High-level command and status variables.
 *
 * The serial console sets request flags such as "start" and "stop". The state
 * machine consumes those requests later. This keeps command parsing separate
 * from safety-critical switching decisions.
 */
volatile bool mppt_start_requested = false;
volatile bool mppt_stop_requested = false;
volatile bool mppt_fault_reset_requested = false;
volatile MpptState_t mppt_state = MPPT_STATE_INIT;
volatile MpptFault_t mppt_fault = MPPT_FAULT_NONE;

/* Internal controller state used only inside this file. */
static MpptMeasurements_t mppt_measurements = {0};
static MpptDutyCommand_t mppt_command = {0};
static uint32_t mppt_state_entered_ms = 0U;
static uint32_t fast_task_last_ms = 0U;
static uint32_t mppt_task_last_ms = 0U;
static uint32_t telemetry_task_last_ms = 0U;
static uint32_t telemetry_sequence = 0U;
static bool power_stage_pwm_running = false;
static float input_current_offset_v = 0.0f;
static float output_current_offset_v = 0.0f;
static MpptState_t ld3_status_previous_state = MPPT_STATE_INIT;
static uint32_t ld3_status_pattern_started_ms = 0U;
static uint8_t serial_console_rx_byte = 0U;
static volatile uint8_t serial_console_pending_command = 0U;
static volatile bool serial_console_command_pending = false;

/* Forward declarations keep main() near the top while functions remain grouped by purpose below. */
void SystemClock_Config(void);
static void Mppt_Init(void);
static void Mppt_StateMachineTask(void);
static void Mppt_SetState(MpptState_t next_state);
static void Mppt_EnterFault(MpptFault_t fault);
static bool Mppt_RunFastTasks(void);
static MpptDutyCommand_t Mppt_CalculateDuty(float panel_voltage_v, float panel_current_a);
static bool Measurements_Update(void);
static bool Measurements_AreInAdcRange(const MpptMeasurements_t *measurements);
static void Measurements_CaptureZeroCurrentOffsets(void);
static float Measurements_InputVoltageFromAdc(float adc_voltage);
static float Measurements_OutputVoltageFromAdc(float adc_voltage);
static float Measurements_InputCurrentFromAdc(float adc_voltage);
static float Measurements_OutputCurrentFromAdc(float adc_voltage);
static bool Adc_ReadChannel(ADC_HandleTypeDef *hadc, uint32_t channel, uint16_t *raw_count);
static float Adc_RawToVolts(uint16_t raw_count);
static void PowerStage_Disable(void);
static bool PowerStage_Enable(void);
static void PowerStage_SetDuty(float buck_duty, float boost_duty);
static uint32_t Pwm_DutyToCompare(float duty);
static float ClampFloat(float value, float min_value, float max_value);
static bool TimeElapsed(uint32_t now_ms, uint32_t last_ms, uint32_t period_ms);
static void Mppt_Update(void);
static const char *Mppt_StateName(MpptState_t state);
static const char *Mppt_FaultName(MpptFault_t fault);
static void SerialConsole_Init(void);
static void SerialConsole_Task(void);
static void SerialConsole_StartReceive(void);
static void SerialConsole_ProcessCommand(uint8_t command);
static void SerialConsole_PrintBootMessage(void);
static void SerialConsole_PrintHelp(void);
static void SerialConsole_PrintStatus(void);
static void SerialConsole_Send(const char *text);
static void SerialConsole_SendLine(const char *text);
static void Ld3Status_TestTask(MpptState_t state);
static void Ld3Status_ApplyPattern(uint32_t period_ms, uint32_t on_time_ms);
static void Ld3Status_Set(bool led_on);
static void Telemetry_Task(void);

/**
  * @brief  Initializes HAL, clocks, peripherals, serial console, and the MPPT control loop.
  */
int main(void)
{
  /* HAL_Init() prepares the STM32 HAL library and starts the 1 ms system tick. */
  HAL_Init();

  /* Configure the MCU clock tree before peripherals that depend on timer clocks. */
  SystemClock_Config();

  /* CubeMX-generated peripheral setup. These functions configure pins, ADCs,
   * timers, and UARTs, but they do not by themselves implement MPPT control. */
  MX_GPIO_Init();
  MX_ADC1_Init();
  MX_ADC2_Init();
  MX_TIM1_Init();
  MX_USART1_UART_Init();
  MX_TIM3_Init();
  MX_USART2_UART_Init();

  /* Start the PC console first so boot messages and fault states are visible. */
  SerialConsole_Init();
  SerialConsole_PrintBootMessage();

  /* Initialise the converter controller. This keeps the power stage disabled,
   * calibrates the ADCs, captures current-sensor offsets, and then enters IDLE. */
  Mppt_Init();
  SerialConsole_PrintStatus();

  /*
   * Cooperative super-loop.
   *
   * There is no operating system here. Each task must return quickly so the
   * next task can run on time. Avoid long blocking delays inside this loop.
   */
  while (1)
  {
    /* Handles one-byte user commands received over USART2. */
    SerialConsole_Task();

    /* Runs measurement, protection, state transitions, and MPPT updates. */
    Mppt_StateMachineTask();

    /* Test-only status indication on LD3/PB3. See the warning in the function. */
    Ld3Status_TestTask((MpptState_t)mppt_state);
  }
}

/**
  * @brief  Configures the HSI PLL system clock and USART1/TIM1 peripheral clocks.
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /* Use the internal HSI oscillator and multiply it with the PLL. The resulting
   * system clock sets the timing base for the CPU and several peripherals. */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL16;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /* Configure the bus clock dividers. These settings affect peripheral timing,
   * including UART baud rates and timer counter frequencies. */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }

  /* TIM1 is the advanced timer used for the complementary PWM outputs. Its
   * clock selection must be consistent with the CubeMX PWM-period settings. */
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART1|RCC_PERIPHCLK_TIM1;
  PeriphClkInit.Usart1ClockSelection = RCC_USART1CLKSOURCE_SYSCLK;
  PeriphClkInit.Tim1ClockSelection = RCC_TIM1CLK_PLLCLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief  Forces safe outputs, calibrates ADCs, captures current-sensor offsets,
  *         and places the converter controller in IDLE.
  */
static void Mppt_Init(void)
{
  /* The first firmware action for the converter controller is always safe output. */
  PowerStage_Disable();

  /* ADC calibration compensates internal ADC errors before readings are trusted. */
  if ((HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED) != HAL_OK) ||
      (HAL_ADCEx_Calibration_Start(&hadc2, ADC_SINGLE_ENDED) != HAL_OK))
  {
    Mppt_EnterFault(MPPT_FAULT_ADC_READ);
    return;
  }

  /* Take one measurement before offset calibration so the current-sensor zero
   * points can be stored while no converter current should be flowing. */
  if (!Measurements_Update())
  {
    Mppt_EnterFault(MPPT_FAULT_ADC_READ);
    return;
  }

  Measurements_CaptureZeroCurrentOffsets();

  /* Re-read after offset capture so converted current values use the new offsets. */
  (void)Measurements_Update();
  Mppt_SetState(MPPT_STATE_IDLE);
}

/**
  * @brief  Runs the top-level MPPT converter state machine from the main loop.
  */
static void Mppt_StateMachineTask(void)
{
  const uint32_t now_ms = HAL_GetTick();

  /* Fast task: refresh measurements and perform simple feedback validity checks. */
  if (TimeElapsed(now_ms, fast_task_last_ms, FAST_TASK_PERIOD_MS))
  {
    fast_task_last_ms = now_ms;
    (void)Mppt_RunFastTasks();
  }

  /* Telemetry is intentionally slower than measurement/protection. */
  if (TimeElapsed(now_ms, telemetry_task_last_ms, TELEMETRY_TASK_PERIOD_MS))
  {
    telemetry_task_last_ms = now_ms;
    Telemetry_Task();
  }

  switch ((MpptState_t)mppt_state)
  {
    case MPPT_STATE_INIT:
      /* If the controller ever reaches INIT after boot, return to a safe idle state. */
      Mppt_SetState(MPPT_STATE_IDLE);
      break;

    case MPPT_STATE_IDLE:
      /* IDLE is the safe waiting state. A start request is accepted only when
       * the latest ADC readings are valid and not saturated. */
      if (mppt_start_requested)
      {
        mppt_start_requested = false;
        if (mppt_measurements.valid && Measurements_AreInAdcRange(&mppt_measurements))
        {
          Mppt_SetState(MPPT_STATE_STARTUP);
        }
        else
        {
          Mppt_EnterFault(MPPT_FAULT_ADC_READ);
        }
      }
      break;

    case MPPT_STATE_STARTUP:
      /* STARTUP applies a small known duty command and waits for the converter
       * to settle before handing control to the student MPPT algorithm. */
      if (mppt_stop_requested)
      {
        mppt_stop_requested = false;
        Mppt_SetState(MPPT_STATE_IDLE);
      }
      else if (TimeElapsed(now_ms, mppt_state_entered_ms, STARTUP_SETTLE_TIME_MS))
      {
        Mppt_SetState(MPPT_STATE_RUN);
      }
      break;

    case MPPT_STATE_RUN:
      /* RUN executes the MPPT algorithm at a medium rate. The duty cycle is not
       * updated every loop iteration, because the power stage and ADC readings
       * need time to respond after each command change. */
      if (mppt_stop_requested)
      {
        mppt_stop_requested = false;
        Mppt_SetState(MPPT_STATE_IDLE);
        break;
      }

      if (TimeElapsed(now_ms, mppt_task_last_ms, MPPT_TASK_PERIOD_MS))
      {
        mppt_task_last_ms = now_ms;
        Mppt_Update();
      }

      break;

    case MPPT_STATE_FAULT:
    default:
      /* FAULT is latched. Keep switching disabled until a deliberate reset request. */
      PowerStage_Disable();
      if (mppt_fault_reset_requested)
      {
        mppt_fault_reset_requested = false;
        mppt_stop_requested = false;
        mppt_start_requested = false;
        mppt_fault = MPPT_FAULT_NONE;
        Mppt_SetState(MPPT_STATE_IDLE);
      }
      break;
  }
}

/**
  * @brief  Enters a new converter state and performs the required entry action.
  * @param  next_state State to enter.
  */
static void Mppt_SetState(MpptState_t next_state)
{
  mppt_state = next_state;
  mppt_state_entered_ms = HAL_GetTick();

  switch (next_state)
  {
    case MPPT_STATE_INIT:
    case MPPT_STATE_IDLE:
      /* In non-switching states, force the converter outputs to the safe state. */
      PowerStage_Disable();
      break;

    case MPPT_STATE_STARTUP:
      /* Start with a small fixed command. Students should verify this on an
       * oscilloscope before using real PV panels or a battery/load. */
      mppt_command.buck_duty = STARTUP_BUCK_DUTY;
      mppt_command.boost_duty = STARTUP_BOOST_DUTY;
      PowerStage_SetDuty(mppt_command.buck_duty, mppt_command.boost_duty);
      if (!PowerStage_Enable())
      {
        Mppt_EnterFault(MPPT_FAULT_PWM_START);
      }
      break;

    case MPPT_STATE_RUN:
      /* RUN keeps the PWM hardware enabled. Mppt_Update() later changes compare values. */
      if (!PowerStage_Enable())
      {
        Mppt_EnterFault(MPPT_FAULT_PWM_START);
      }
      break;

    case MPPT_STATE_FAULT:
    default:
      /* Any unknown state is treated as a fault-like condition. */
      PowerStage_Disable();
      break;
  }
}

/**
  * @brief  Latches the fault reason and immediately moves the converter to FAULT.
  * @param  fault Fault code to store for debugging or telemetry.
  */
static void Mppt_EnterFault(MpptFault_t fault)
{
  /* Store the cause before changing state so it can be printed and debugged. */
  mppt_fault = fault;
  Mppt_SetState(MPPT_STATE_FAULT);
}

/**
  * @brief  Runs high-rate measurement and protection checks.
  * @retval true when fast tasks completed without tripping a fault.
  */
static bool Mppt_RunFastTasks(void)
{
  const MpptState_t current_state = (MpptState_t)mppt_state;

  /* A failed ADC update means the controller no longer knows the converter state. */
  if (!Measurements_Update())
  {
    if (current_state != MPPT_STATE_FAULT)
    {
      Mppt_EnterFault(MPPT_FAULT_ADC_READ);
      return false;
    }

    return false;
  }

  /* Saturated ADC values are treated as invalid feedback while switching is active. */
  if (((current_state == MPPT_STATE_STARTUP) || (current_state == MPPT_STATE_RUN)) &&
      !Measurements_AreInAdcRange(&mppt_measurements))
  {
    Mppt_EnterFault(MPPT_FAULT_ADC_RANGE);
    return false;
  }

  return true;
}

/**
  * @brief  Student MPPT algorithm hook.
  * @param  panel_voltage_v Input/PV voltage in volts.
  * @param  panel_current_a Input/PV current in amps.
  * @retval Buck and boost duty-cycle command requested by the MPPT algorithm.
  */
static MpptDutyCommand_t Mppt_CalculateDuty(float panel_voltage_v, float panel_current_a)
{
  /* Start from the previous command. If students do not change anything below,
   * the converter will hold its last duty cycle instead of jumping abruptly. */
  MpptDutyCommand_t next_command = mppt_command;

  /* MPPT is based on input-side PV power, not output power. The guide defines
   * this as P_PV = V_in * I_in. */
  const float panel_power_w = panel_voltage_v * panel_current_a;

  /*
   * STUDENT MPPT CODE GOES HERE.
   *
   * Use panel_voltage_v, panel_current_a, and panel_power_w to decide how the
   * converter should move. Typical algorithms compare the present power with a
   * previous power value, then perturb the duty command in the direction that
   * increased PV power.
   *
   * Set one or both command fields:
   *
   *   next_command.buck_duty
   *   next_command.boost_duty
   *
   * The values are normalised duties from 0.0 to 1.0. PowerStage_SetDuty() will
   * clamp them to DUTY_MIN/DUTY_MAX before writing the timer compare registers.
   *
   * Keep the MPPT step size small. A large duty step can collapse the PV voltage
   * or cause a current transient before the ADC readings settle.
   */
  (void)panel_power_w;

  return next_command;
}

/**
  * @brief  Polls all ADC feedback channels and converts them to engineering units.
  * @retval true when all ADC conversions completed successfully.
  */
static bool Measurements_Update(void)
{
  bool ok = true;

  /* Read the four analogue feedback channels listed in the guide's STM32 pin map. */
  ok = ok && Adc_ReadChannel(&hadc1, ADC_CHANNEL_1, &mppt_measurements.i_in_raw);
  ok = ok && Adc_ReadChannel(&hadc1, ADC_CHANNEL_2, &mppt_measurements.i_out_raw);
  ok = ok && Adc_ReadChannel(&hadc2, ADC_CHANNEL_1, &mppt_measurements.v_out_raw);
  ok = ok && Adc_ReadChannel(&hadc2, ADC_CHANNEL_2, &mppt_measurements.v_in_raw);

  /* First convert raw ADC counts to voltages at the STM32 pins. */
  mppt_measurements.i_in_adc_v = Adc_RawToVolts(mppt_measurements.i_in_raw);
  mppt_measurements.i_out_adc_v = Adc_RawToVolts(mppt_measurements.i_out_raw);
  mppt_measurements.v_out_adc_v = Adc_RawToVolts(mppt_measurements.v_out_raw);
  mppt_measurements.v_in_adc_v = Adc_RawToVolts(mppt_measurements.v_in_raw);

  /* Then convert sensor output voltages to physical converter quantities. */
  mppt_measurements.i_in_a = Measurements_InputCurrentFromAdc(mppt_measurements.i_in_adc_v);
  mppt_measurements.i_out_a = Measurements_OutputCurrentFromAdc(mppt_measurements.i_out_adc_v);
  mppt_measurements.v_out_v = Measurements_OutputVoltageFromAdc(mppt_measurements.v_out_adc_v);
  mppt_measurements.v_in_v = Measurements_InputVoltageFromAdc(mppt_measurements.v_in_adc_v);

  /* Store PV input power for telemetry/debugging. The MPPT hook calculates the
   * same quantity from its input arguments. */
  mppt_measurements.pv_power_w = mppt_measurements.v_in_v * mppt_measurements.i_in_a;
  mppt_measurements.valid = ok;
  mppt_measurements.updated_ms = HAL_GetTick();

  return ok;
}

/**
  * @brief  Checks for saturated ADC readings that indicate invalid feedback.
  * @param  measurements Latest converted measurement packet.
  * @retval true when all ADC channels are inside the usable ADC range.
  */
static bool Measurements_AreInAdcRange(const MpptMeasurements_t *measurements)
{
  /* This check only catches obviously unusable readings close to full-scale ADC
   * saturation. Practical over-voltage and over-current limits should be added
   * separately once the approved laboratory limits are known. */
  return (measurements->valid &&
          (measurements->i_in_raw < ADC_RAW_SATURATION_COUNT) &&
          (measurements->i_out_raw < ADC_RAW_SATURATION_COUNT) &&
          (measurements->v_out_raw < ADC_RAW_SATURATION_COUNT) &&
          (measurements->v_in_raw < ADC_RAW_SATURATION_COUNT));
}

/**
  * @brief  Stores the present current-sensor ADC voltages as zero-current offsets.
  */
static void Measurements_CaptureZeroCurrentOffsets(void)
{
  /* Current sensors usually do not output exactly 0 V at 0 A. Store their present
   * no-load voltages and subtract them from later current measurements. */
  input_current_offset_v = mppt_measurements.i_in_adc_v;
  output_current_offset_v = mppt_measurements.i_out_adc_v;
}

/**
  * @brief  Converts input-voltage sensor ADC voltage to panel/input voltage.
  * @param  adc_voltage ADC pin voltage from ADC2_IN2.
  * @retval Estimated panel/input voltage in volts.
  */
static float Measurements_InputVoltageFromAdc(float adc_voltage)
{
  /* V_in = V_ADC multiplied by the input-voltage divider/sensor scale factor. */
  return adc_voltage * INPUT_VOLTAGE_SENSOR_SCALE;
}

/**
  * @brief  Converts output-voltage sensor ADC voltage to converter output voltage.
  * @param  adc_voltage ADC pin voltage from ADC2_IN1.
  * @retval Estimated converter output voltage in volts.
  */
static float Measurements_OutputVoltageFromAdc(float adc_voltage)
{
  /* V_out = V_ADC multiplied by the output-voltage divider/sensor scale factor. */
  return adc_voltage * OUTPUT_VOLTAGE_SENSOR_SCALE;
}

/**
  * @brief  Converts input-current sensor ADC voltage to panel/input current.
  * @param  adc_voltage ADC pin voltage from ADC1_IN1.
  * @retval Estimated panel/input current in amps.
  */
static float Measurements_InputCurrentFromAdc(float adc_voltage)
{
  /* I_in = (sensor voltage - zero-current offset) / sensor sensitivity. */
  return (adc_voltage - input_current_offset_v) / INPUT_CURRENT_SENSOR_V_PER_A;
}

/**
  * @brief  Converts output-current sensor ADC voltage to converter output current.
  * @param  adc_voltage ADC pin voltage from ADC1_IN2.
  * @retval Estimated converter output current in amps.
  */
static float Measurements_OutputCurrentFromAdc(float adc_voltage)
{
  /* I_out uses the output sensor's sensitivity, which differs from the input sensor. */
  return (adc_voltage - output_current_offset_v) / OUTPUT_CURRENT_SENSOR_V_PER_A;
}

/**
  * @brief  Selects one ADC channel, performs one blocking conversion, and returns
  *         the raw ADC count.
  * @param  hadc ADC instance to use.
  * @param  channel ADC channel number.
  * @param  raw_count Destination for the 12-bit ADC result.
  * @retval true when the conversion completed successfully.
  */
static bool Adc_ReadChannel(ADC_HandleTypeDef *hadc, uint32_t channel, uint16_t *raw_count)
{
  ADC_ChannelConfTypeDef sConfig = {0};

  /* Select one ADC input channel for this conversion. This project polls channels
   * one at a time to keep the scaffold explicit for students. */
  sConfig.Channel = channel;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SingleDiff = ADC_SINGLE_ENDED;
  sConfig.SamplingTime = ADC_SAMPLETIME_19CYCLES_5;
  sConfig.OffsetNumber = ADC_OFFSET_NONE;
  sConfig.Offset = 0;

  if (HAL_ADC_ConfigChannel(hadc, &sConfig) != HAL_OK)
  {
    return false;
  }

  if (HAL_ADC_Start(hadc) != HAL_OK)
  {
    return false;
  }

  /* This is a blocking wait with a short timeout. It is acceptable for a teaching
   * scaffold, but higher-performance versions usually use DMA or interrupts. */
  if (HAL_ADC_PollForConversion(hadc, ADC_POLL_TIMEOUT_MS) != HAL_OK)
  {
    (void)HAL_ADC_Stop(hadc);
    return false;
  }

  *raw_count = (uint16_t)HAL_ADC_GetValue(hadc);
  (void)HAL_ADC_Stop(hadc);
  return true;
}

/**
  * @brief  Converts a 12-bit ADC count to ADC input-pin voltage.
  * @param  raw_count Raw ADC count.
  * @retval ADC input-pin voltage in volts.
  */
static float Adc_RawToVolts(uint16_t raw_count)
{
  /* For a 12-bit ADC, 4095 counts corresponds approximately to V_REF. */
  return ((float)raw_count * ADC_REFERENCE_VOLTAGE) / ADC_MAX_COUNTS;
}

/**
  * @brief  Immediately disables both gate drivers, commands zero PWM compare,
  *         and stops all TIM1 PWM outputs.
  */
static void PowerStage_Disable(void)
{
  /* The gate-driver disable pins are active high. Set them first so the driver
   * outputs are disabled before PWM registers or timer channels are changed. */
  HAL_GPIO_WritePin(BST_DIS_GPIO_Port, BST_DIS_Pin, GPIO_PIN_SET);
  HAL_GPIO_WritePin(BCK_DIS_GPIO_Port, BCK_DIS_Pin, GPIO_PIN_SET);

  /* A compare value of zero requests 0% duty on both PWM channels. */
  __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, 0U);
  __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_2, 0U);

  /* Stop both the main and complementary outputs for the two TIM1 channels. */
  (void)HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_1);
  (void)HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_1);
  (void)HAL_TIM_PWM_Stop(&htim1, TIM_CHANNEL_2);
  (void)HAL_TIMEx_PWMN_Stop(&htim1, TIM_CHANNEL_2);
  power_stage_pwm_running = false;
}

/**
  * @brief  Starts TIM1 main/complementary PWM outputs and releases the gate-driver
  *         disable pins.
  * @retval true when PWM outputs are running and drivers are enabled.
  */
static bool PowerStage_Enable(void)
{
  if (!power_stage_pwm_running)
  {
    /* Start the high-side/low-side complementary outputs before releasing the
     * gate-driver disable pins. If any start call fails, return to the safe state. */
    if ((HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_1) != HAL_OK) ||
        (HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_1) != HAL_OK) ||
        (HAL_TIM_PWM_Start(&htim1, TIM_CHANNEL_2) != HAL_OK) ||
        (HAL_TIMEx_PWMN_Start(&htim1, TIM_CHANNEL_2) != HAL_OK))
    {
      PowerStage_Disable();
      return false;
    }

    power_stage_pwm_running = true;
  }

  /* RESET clears the active-high disable signal, allowing the drivers to switch. */
  HAL_GPIO_WritePin(BST_DIS_GPIO_Port, BST_DIS_Pin, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(BCK_DIS_GPIO_Port, BCK_DIS_Pin, GPIO_PIN_RESET);
  return true;
}

/**
  * @brief  Applies buck and boost duty commands to TIM1 compare registers.
  * @param  buck_duty Duty command for the buck bridge.
  * @param  boost_duty Duty command for the boost bridge.
  */
static void PowerStage_SetDuty(float buck_duty, float boost_duty)
{
  /* Clamp first so no algorithm can request an unsafe 100% duty or a negative duty. */
  mppt_command.buck_duty = ClampFloat(buck_duty, DUTY_MIN, DUTY_MAX);
  mppt_command.boost_duty = ClampFloat(boost_duty, DUTY_MIN, DUTY_MAX);

  /* TIM1 channel 1 drives the buck bridge command; TIM1 channel 2 drives the
   * boost bridge command. CubeMX configures the complementary outputs/dead time. */
  __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, Pwm_DutyToCompare(mppt_command.buck_duty));
  __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_2, Pwm_DutyToCompare(mppt_command.boost_duty));
}

/**
  * @brief  Converts a normalized duty value into a TIM1 compare value.
  * @param  duty Duty command from 0.0 to 1.0 before clamping.
  * @retval Timer compare value corresponding to the requested duty.
  */
static uint32_t Pwm_DutyToCompare(float duty)
{
  /* The auto-reload register is the timer period. The compare register selects
   * where within that period the PWM output changes state. */
  const uint32_t auto_reload = __HAL_TIM_GET_AUTORELOAD(&htim1);
  uint32_t compare = (uint32_t)(ClampFloat(duty, DUTY_MIN, DUTY_MAX) *
                               (float)(auto_reload + 1U));

  /* Prevent a compare value larger than the timer period. */
  if (compare > auto_reload)
  {
    compare = auto_reload;
  }

  return compare;
}

/**
  * @brief  Limits a floating-point value to a minimum and maximum.
  * @param  value Value to clamp.
  * @param  min_value Lower allowed value.
  * @param  max_value Upper allowed value.
  * @retval Clamped value.
  */
static float ClampFloat(float value, float min_value, float max_value)
{
  if (value < min_value)
  {
    return min_value;
  }

  if (value > max_value)
  {
    return max_value;
  }

  return value;
}

/**
  * @brief  Checks elapsed time using unsigned tick arithmetic.
  * @param  now_ms Current HAL tick in milliseconds.
  * @param  last_ms Previous task execution tick.
  * @param  period_ms Required task period in milliseconds.
  * @retval true when the requested period has elapsed.
  */
static bool TimeElapsed(uint32_t now_ms, uint32_t last_ms, uint32_t period_ms)
{
  /* Unsigned subtraction still works correctly when HAL_GetTick() wraps around. */
  return ((uint32_t)(now_ms - last_ms) >= period_ms);
}

/**
  * @brief  Runs the medium-rate MPPT update and applies the returned duty command.
  */
static void Mppt_Update(void)
{
  /* The MPPT algorithm receives input-side PV voltage and current. */
  MpptDutyCommand_t next_command =
      Mppt_CalculateDuty(mppt_measurements.v_in_v, mppt_measurements.i_in_a);

  /* The power-stage layer clamps and applies the returned command. */
  PowerStage_SetDuty(next_command.buck_duty, next_command.boost_duty);
}

/**
  * @brief  Returns a text label for an MPPT state.
  * @param  state MPPT state.
  * @retval Constant string for serial status output.
  */
static const char *Mppt_StateName(MpptState_t state)
{
  switch (state)
  {
    case MPPT_STATE_INIT:
      return "INIT";
    case MPPT_STATE_IDLE:
      return "IDLE";
    case MPPT_STATE_STARTUP:
      return "STARTUP";
    case MPPT_STATE_RUN:
      return "RUN";
    case MPPT_STATE_FAULT:
      return "FAULT";
    default:
      return "UNKNOWN";
  }
}

/**
  * @brief  Returns a text label for an MPPT fault code.
  * @param  fault MPPT fault code.
  * @retval Constant string for serial status output.
  */
static const char *Mppt_FaultName(MpptFault_t fault)
{
  switch (fault)
  {
    case MPPT_FAULT_NONE:
      return "NONE";
    case MPPT_FAULT_ADC_READ:
      return "ADC_READ";
    case MPPT_FAULT_ADC_RANGE:
      return "ADC_RANGE";
    case MPPT_FAULT_PWM_START:
      return "PWM_START";
    default:
      return "UNKNOWN";
  }
}

/**
  * @brief  Starts the USART2 PC-console receive interrupt.
  */
static void SerialConsole_Init(void)
{
  /* USART2 is used as the PC console in this scaffold. Reception is interrupt
   * driven one byte at a time so the main loop does not have to wait for input. */
  SerialConsole_StartReceive();
}

/**
  * @brief  Handles pending PC-console commands outside the UART interrupt.
  */
static void SerialConsole_Task(void)
{
  uint8_t command;

  /* If no UART callback has supplied a new command byte, this task does nothing. */
  if (!serial_console_command_pending)
  {
    return;
  }

  /* Copy and clear the pending command before processing it. This keeps the UART
   * callback short and leaves command effects to the main-loop context. */
  command = serial_console_pending_command;
  serial_console_command_pending = false;
  SerialConsole_ProcessCommand(command);
}

/**
  * @brief  Arms one-byte interrupt receive on the USART2 PC console.
  */
static void SerialConsole_StartReceive(void)
{
  /* Arm reception for exactly one byte. The receive-complete callback below
   * stores that byte and then calls this function again. */
  (void)HAL_UART_Receive_IT(&huart2, &serial_console_rx_byte, 1U);
}

/**
  * @brief  Converts received serial characters into MPPT state requests.
  * @param  command Received ASCII command.
  */
static void SerialConsole_ProcessCommand(uint8_t command)
{
  switch (command)
  {
    case 's':
    case 'S':
      /* Request a transition from IDLE to STARTUP. The state machine checks
       * measurements before it actually enables switching. */
      mppt_start_requested = true;
      mppt_stop_requested = false;
      SerialConsole_SendLine("Start requested");
      break;

    case 'x':
    case 'X':
      /* Request a controlled stop. The state machine will disable the power stage. */
      mppt_stop_requested = true;
      mppt_start_requested = false;
      SerialConsole_SendLine("Stop requested");
      break;

    case 'r':
    case 'R':
      /* Fault reset is deliberate. It clears the latched fault only in FAULT state. */
      mppt_fault_reset_requested = true;
      SerialConsole_SendLine("Fault reset requested");
      break;

    case '?':
      /* Print the present state and fault code without changing control state. */
      SerialConsole_PrintStatus();
      break;

    case 'h':
    case 'H':
      SerialConsole_PrintHelp();
      break;

    case '\r':
    case '\n':
      break;

    default:
      SerialConsole_SendLine("Unknown command");
      SerialConsole_PrintHelp();
      break;
  }
}

/**
  * @brief  Prints the startup banner and command summary.
  */
static void SerialConsole_PrintBootMessage(void)
{
  SerialConsole_SendLine("");
  SerialConsole_SendLine("ENR MPPT boot");
  SerialConsole_PrintHelp();
}

/**
  * @brief  Prints the available serial-console commands.
  */
static void SerialConsole_PrintHelp(void)
{
  SerialConsole_SendLine("Commands: s=start, x=stop, r=reset fault, ?=status, h=help");
}

/**
  * @brief  Prints current state and latched fault over USART2.
  */
static void SerialConsole_PrintStatus(void)
{
  SerialConsole_Send("State: ");
  SerialConsole_SendLine(Mppt_StateName((MpptState_t)mppt_state));
  SerialConsole_Send("Fault: ");
  SerialConsole_SendLine(Mppt_FaultName((MpptFault_t)mppt_fault));
}

/**
  * @brief  Sends a null-terminated string over the USART2 PC console.
  * @param  text String to transmit.
  */
static void SerialConsole_Send(const char *text)
{
  (void)HAL_UART_Transmit(&huart2,
                          (uint8_t *)text,
                          (uint16_t)strlen(text),
                          100U);
}

/**
  * @brief  Sends a null-terminated string followed by CRLF over USART2.
  * @param  text String to transmit.
  */
static void SerialConsole_SendLine(const char *text)
{
  SerialConsole_Send(text);
  SerialConsole_Send("\r\n");
}

/**
  * @brief  UART receive-complete callback used by the USART2 PC console.
  * @param  huart UART handle that completed reception.
  */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
  if (huart->Instance == USART2)
  {
    /* Interrupt callbacks should be short. Store the byte and let
     * SerialConsole_Task() process it from the main loop. */
    serial_console_pending_command = serial_console_rx_byte;
    serial_console_command_pending = true;
    SerialConsole_StartReceive();
  }
}

/**
  * @brief  UART error callback; restarts the USART2 PC-console receiver.
  * @param  huart UART handle that reported an error.
  */
void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
  if (huart->Instance == USART2)
  {
    /* If a UART framing/noise/overrun error occurs, re-arm reception so the
     * console can recover without resetting the MCU. */
    SerialConsole_StartReceive();
  }
}

/**
  * @brief  Test-only LD3 status LED task.
  * @param  state Current MPPT state to display on LD3.
  *
  * LD3 is on D13/PB3. In this project PB3 is also BST_STP, so this must only be
  * used while testing without an energised converter.
  */
static void Ld3Status_TestTask(MpptState_t state)
{
#if (LD3_STATUS_TEST_ENABLE != 0U)
  /* Restart the blink pattern whenever the displayed state changes. */
  if (state != ld3_status_previous_state)
  {
    ld3_status_previous_state = state;
    ld3_status_pattern_started_ms = HAL_GetTick();
  }

  switch (state)
  {
    case MPPT_STATE_IDLE:
      /* Slow blink: controller is safe and waiting for a start command. */
      Ld3Status_ApplyPattern(LD3_IDLE_PERIOD_MS, LD3_IDLE_ON_TIME_MS);
      break;

    case MPPT_STATE_RUN:
      /* Faster blink: MPPT updates are active. Use only during non-energised tests. */
      Ld3Status_ApplyPattern(LD3_RUN_PERIOD_MS, LD3_RUN_ON_TIME_MS);
      break;

    case MPPT_STATE_INIT:
    case MPPT_STATE_STARTUP:
    case MPPT_STATE_FAULT:
    default:
      Ld3Status_Set(false);
      break;
  }
#else
  (void)state;
  Ld3Status_Set(false);
#endif
}

/**
  * @brief  Applies a repeating on/off LED pattern.
  * @param  period_ms Total pattern period in milliseconds.
  * @param  on_time_ms Time within the period for which LD3 is on.
  */
static void Ld3Status_ApplyPattern(uint32_t period_ms, uint32_t on_time_ms)
{
  const uint32_t phase_ms =
      (uint32_t)(HAL_GetTick() - ld3_status_pattern_started_ms) % period_ms;

  Ld3Status_Set(phase_ms < on_time_ms);
}

/**
  * @brief  Drives LD3 on the Nucleo board through the shared D13/PB3 pin.
  * @param  led_on true turns LD3 on, false turns LD3 off.
  */
static void Ld3Status_Set(bool led_on)
{
  HAL_GPIO_WritePin(BST_STP_GPIO_Port, BST_STP_Pin,
                    led_on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/**
  * @brief  Sends one raw-ADC telemetry packet over the USART2 PC console.
  *
  * Packet format:
  * ADC,ms,seq,i_in_raw,i_out_raw,v_out_raw,v_in_raw,valid,state,fault
  */
static void Telemetry_Task(void)
{
  char line[128];

  /* The packet intentionally reports raw ADC counts as well as state/fault text.
   * Raw counts are useful when students are checking ADC wiring and scaling. */
  const int length = snprintf(line,
                              sizeof(line),
                              "ADC,%lu,%lu,%u,%u,%u,%u,%u,%s,%s\r\n",
                              (unsigned long)mppt_measurements.updated_ms,
                              (unsigned long)telemetry_sequence++,
                              mppt_measurements.i_in_raw,
                              mppt_measurements.i_out_raw,
                              mppt_measurements.v_out_raw,
                              mppt_measurements.v_in_raw,
                              mppt_measurements.valid ? 1U : 0U,
                              Mppt_StateName((MpptState_t)mppt_state),
                              Mppt_FaultName((MpptFault_t)mppt_fault));

  /* Send only complete packets that fit in the local buffer. */
  if ((length > 0) && ((size_t)length < sizeof(line)))
  {
    SerialConsole_Send(line);
  }
}

/**
  * @brief  Stops execution after a non-recoverable HAL or configuration error.
  */
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Handles failed full-assert checks during debug builds.
  * @param  file Source file that triggered the assertion.
  * @param  line Source line that triggered the assertion.
  */
void assert_failed(uint8_t *file, uint32_t line)
{
}
#endif
